language: objective-c
osx_image: xcode7

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && pod install && rake build | xcpretty -c
#- pod lib lint --quick GenumKit/GenumKit.podspec
