// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Airing :Media,PlayableMedia,WatchlistBookmarksPersonalizedHit {
    var contentId: String
    var displayRunTime: String?
    var genres: [String?]?
    var programId: String?
    var runTime: String?
    var type: String
    var mediaId: String?
    var milestones: [Milestone?]?
    var playbackUrls: [HypermediaLink?]?
    var user: WatchlistBookmarksUser?
    var actorsDisplay: String?
    var adId: String?
    var captionLanguages: [String?]?
    var channel: EpgChannel?
    var endDate: String?
    var eventId: String?
    var expires: String?
    var feedLanguage: String?
    var feedType: String?
    var groupingId: String?
    var keywords: EpgKeywords?
    var linear: Bool?
    var mediaConfig: EpgMediaConfig?
    var partnerProgramId: String?
    var photos: [EpgPhoto?]?
    var programType: String?
    var rating: EpgRating?
    var ratings: [Rating?]?
    var slates: [Slate?]?
    var startDate: String?
    var teams: [EpgTeam?]?
    var titles: [EpgTitle?]?
    var liveBroadcast: Bool?
    var runtimeMillis: Int?
    var slug: String?
    var series_slug: String?
    var season_slug: String?
    var seasonId: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     displayRunTime =  unboxer.unbox(key: "displayRunTime")
     genres =  unboxer.unbox(key: "genres")
     programId =  unboxer.unbox(key: "programId")
     runTime =  unboxer.unbox(key: "runTime")
     type = try unboxer.unbox(key: "type")
     mediaId =  unboxer.unbox(key: "mediaId")
     milestones =  unboxer.unbox(key: "milestones")
     playbackUrls =  unboxer.unbox(key: "playbackUrls")
     user =  unboxer.unbox(key: "user")
     actorsDisplay =  unboxer.unbox(key: "actorsDisplay")
     adId =  unboxer.unbox(key: "adId")
     captionLanguages =  unboxer.unbox(key: "captionLanguages")
     channel =  unboxer.unbox(key: "channel")
     endDate =  unboxer.unbox(key: "endDate")
     eventId =  unboxer.unbox(key: "eventId")
     expires =  unboxer.unbox(key: "expires")
     feedLanguage =  unboxer.unbox(key: "feedLanguage")
     feedType =  unboxer.unbox(key: "feedType")
     groupingId =  unboxer.unbox(key: "groupingId")
     keywords =  unboxer.unbox(key: "keywords")
     linear =  unboxer.unbox(key: "linear")
     mediaConfig =  unboxer.unbox(key: "mediaConfig")
     partnerProgramId =  unboxer.unbox(key: "partnerProgramId")
     photos =  unboxer.unbox(key: "photos")
     programType =  unboxer.unbox(key: "programType")
     rating =  unboxer.unbox(key: "rating")
     ratings =  unboxer.unbox(key: "ratings")
     slates =  unboxer.unbox(key: "slates")
     startDate =  unboxer.unbox(key: "startDate")
     teams =  unboxer.unbox(key: "teams")
     titles =  unboxer.unbox(key: "titles")
     liveBroadcast =  unboxer.unbox(key: "liveBroadcast")
     runtimeMillis =  unboxer.unbox(key: "runtimeMillis")
     slug =  unboxer.unbox(key: "slug")
     series_slug =  unboxer.unbox(key: "series_slug")
     season_slug =  unboxer.unbox(key: "season_slug")
     seasonId =  unboxer.unbox(key: "seasonId")
  }
}
