// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Airing: Media,PlayableMedia,WatchlistBookmarksPersonalizedHit {
    var contentId: String
    var displayRunTime: String?
    var genres: [String?]?
    var programId: String?
    var runTime: String?
    var type: String
    var mediaId: String?
    var milestones: [Milestone?]?
    var playbackUrls: [HypermediaLink?]?
    var user: WatchlistBookmarksUser?
    var actorsDisplay: String?
    var adId: String?
    var captionLanguages: [String?]?
    var channel: EpgChannel?
    var endDate: String?
    var eventId: String?
    var expires: String?
    var feedLanguage: String?
    var feedType: String?
    var groupingId: String?
    var keywords: EpgKeywords?
    var linear: Bool?
    var mediaConfig: EpgMediaConfig?
    var partnerProgramId: String?
    var photos: [EpgPhoto?]?
    var programType: String?
    var rating: EpgRating?
    var ratings: [Rating?]?
    var slates: [Slate?]?
    var startDate: String?
    var teams: [EpgTeam?]?
    var titles: [EpgTitle?]?
    var liveBroadcast: Bool?
    var runtimeMillis: Int?
    var slug: String?
    var series_slug: String?
    var season_slug: String?
    var seasonId: String?
}
