// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct BoolDirectiveTermsFilter :Unboxable {
    var attributeName: String?
    var values: [String?]?
  init(unboxer: Unboxer) throws { 

  }
}
