// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct BoundingBox :Unboxable {
    var top_left: Coordinate
    var bottom_right: Coordinate
  init(unboxer: Unboxer) throws { 

  }
}
