// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Category: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var defaultAssetImage: [PhotoAsset?]?
    var logoImage: [PhotoAsset?]?
    var sport: String?
}
