// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct ChannelSchedule :Unboxable {
    var channelId: String?
    var videoAirings: [VideoAiringPairing?]?
  init(unboxer: Unboxer) throws { 
     channelId =  unboxer.unbox(key: "channelId")
     videoAirings =  unboxer.unbox(key: "videoAirings")
  }
}
