// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Collection: CmsItem,WatchlistPersonalizedHit {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var user: WatchlistUser?
    var photos: [PhotoAsset?]?
    var title: String?
    var blurb: String?
    var list: [CmsItem?]?
}
