// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Collection :CmsItem,WatchlistPersonalizedHit {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var user: WatchlistUser?
    var photos: [PhotoAsset?]?
    var title: String?
    var blurb: String?
    var list: [CmsItem?]?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     user =  unboxer.unbox(key: "user")
     photos =  unboxer.unbox(key: "photos")
     title =  unboxer.unbox(key: "title")
     blurb =  unboxer.unbox(key: "blurb")
     list =  unboxer.unbox(key: "list")
  }
}
