// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct DeletedBookmark :Unboxable {
    var mediaId: String?
    var userId: String?
    var lastWatched: Date?
    var secondsWatched: Int?
  init(unboxer: Unboxer) throws { 
     mediaId =  unboxer.unbox(key: "mediaId")
     userId =  unboxer.unbox(key: "userId")
     lastWatched =  unboxer.unbox(key: "lastWatched")
     secondsWatched =  unboxer.unbox(key: "secondsWatched")
  }
}
