// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct DeleteAllBookmarks :Unboxable {
    var bookmarks: [DeletedBookmark?]?
    var meta: MetaDeletion?
  init(unboxer: Unboxer) throws { 
     bookmarks =  unboxer.unbox(key: "bookmarks")
     meta =  unboxer.unbox(key: "meta")
  }
}
