// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Dimension :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var width: Int?
    var quality: Int?
    var height: Int?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     width =  unboxer.unbox(key: "width")
     quality =  unboxer.unbox(key: "quality")
     height =  unboxer.unbox(key: "height")
  }
}
