// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

enum DisplayType :String {
    case end = "end"
    case episode = "episode"
  init(unboxer: Unboxer) throws { 

  }
}
