// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EpgChannel :Unboxable {
    var callsign: String?
    var id: String
    var parent: String?
    var partnerId: String?
  init(unboxer: Unboxer) throws { 
     callsign =  unboxer.unbox(key: "callsign")
     id = try unboxer.unbox(key: "id")
     parent =  unboxer.unbox(key: "parent")
     partnerId =  unboxer.unbox(key: "partnerId")
  }
}
