// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EpgKeywords :Unboxable {
    var promos: [String?]?
  init(unboxer: Unboxer) throws { 
     promos =  unboxer.unbox(key: "promos")
  }
}
