// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EpgMediaConfig :Unboxable {
    var state: String?
    var productType: String?
    var type: String?
  init(unboxer: Unboxer) throws { 
     state =  unboxer.unbox(key: "state")
     productType =  unboxer.unbox(key: "productType")
     type =  unboxer.unbox(key: "type")
  }
}
