// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class EpgPhoto {
    var aspectRatio: String?
    var contentSize: String?
    var id: String
    var uri: String?
    var width: Int?
    var height: Int?
}
