// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EpgRating :Unboxable {
    var code: String?
    var system: String?
  init(unboxer: Unboxer) throws { 
     code =  unboxer.unbox(key: "code")
     system =  unboxer.unbox(key: "system")
  }
}
