// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class EpgTitle {
    var descriptionLong: String?
    var descriptionShort: String?
    var episodeName: String?
    var language: String?
    var title: String?
}
