// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EpgTitle :Unboxable {
    var descriptionLong: String?
    var descriptionShort: String?
    var episodeName: String?
    var language: String?
    var title: String?
  init(unboxer: Unboxer) throws { 
     descriptionLong =  unboxer.unbox(key: "descriptionLong")
     descriptionShort =  unboxer.unbox(key: "descriptionShort")
     episodeName =  unboxer.unbox(key: "episodeName")
     language =  unboxer.unbox(key: "language")
     title =  unboxer.unbox(key: "title")
  }
}
