// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class EventPage: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var heroImage: [PhotoAsset?]?
    var tileImage: [PhotoAsset?]?
    var appears: String?
    var bigBlurb: String?
    var endDate: String?
    var expires: String?
    var media: [MediaList?]?
    var publishDestination: String?
    var eventDetails: [EventDetail?]?
    var scheduledPublish: String?
    var startDate: String?
    var subTitle: String?
    var title: String?
}
