// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EventDetail :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var title: String?
    var bigBlurb: String?
    var subTitle: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     title =  unboxer.unbox(key: "title")
     bigBlurb =  unboxer.unbox(key: "bigBlurb")
     subTitle =  unboxer.unbox(key: "subTitle")
  }
}
