// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct EventPage :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var heroImage: [PhotoAsset?]?
    var tileImage: [PhotoAsset?]?
    var appears: String?
    var bigBlurb: String?
    var endDate: String?
    var expires: String?
    var media: [MediaList?]?
    var publishDestination: String?
    var eventDetails: [EventDetail?]?
    var scheduledPublish: String?
    var startDate: String?
    var subTitle: String?
    var title: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     heroImage =  unboxer.unbox(key: "heroImage")
     tileImage =  unboxer.unbox(key: "tileImage")
     appears =  unboxer.unbox(key: "appears")
     bigBlurb =  unboxer.unbox(key: "bigBlurb")
     endDate =  unboxer.unbox(key: "endDate")
     expires =  unboxer.unbox(key: "expires")
     media =  unboxer.unbox(key: "media")
     publishDestination =  unboxer.unbox(key: "publishDestination")
     eventDetails =  unboxer.unbox(key: "eventDetails")
     scheduledPublish =  unboxer.unbox(key: "scheduledPublish")
     startDate =  unboxer.unbox(key: "startDate")
     subTitle =  unboxer.unbox(key: "subTitle")
     title =  unboxer.unbox(key: "title")
  }
}
