// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class EventDetail: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var title: String?
    var bigBlurb: String?
    var subTitle: String?
}
