// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class FieldOption: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var value: String?
    var displayName: String?
}
