// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct FieldOption :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var value: String?
    var displayName: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     value =  unboxer.unbox(key: "value")
     displayName =  unboxer.unbox(key: "displayName")
  }
}
