// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct HypermediaLink :Unboxable {
    var href: String?
    var params: [Param?]?
    var rel: String?
    var templated: Bool?
  init(unboxer: Unboxer) throws { 
     href =  unboxer.unbox(key: "href")
     params =  unboxer.unbox(key: "params")
     rel =  unboxer.unbox(key: "rel")
     templated =  unboxer.unbox(key: "templated")
  }
}
