// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct ImageCut :Unboxable {
    var aspectRatio: String?
    var height: Int?
    var width: Int?
    var src: String?
    var at2x: String?
    var at3x: String?
    var dimensions: String?
  init(unboxer: Unboxer) throws { 
     aspectRatio =  unboxer.unbox(key: "aspectRatio")
     height =  unboxer.unbox(key: "height")
     width =  unboxer.unbox(key: "width")
     src =  unboxer.unbox(key: "src")
     at2x =  unboxer.unbox(key: "at2x")
     at3x =  unboxer.unbox(key: "at3x")
     dimensions =  unboxer.unbox(key: "dimensions")
  }
}
