// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class ImageCut {
    var aspectRatio: String?
    var height: Int?
    var width: Int?
    var src: String?
    var at2x: String?
    var at3x: String?
    var dimensions: String?
}
