// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct KeyVal :Unboxable {
    var key: String?
    var val: String?
  init(unboxer: Unboxer) throws { 
     key =  unboxer.unbox(key: "key")
     val =  unboxer.unbox(key: "val")
  }
}
