// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct KeyValue :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var value: String?
    var listValue: [CmsItem?]?
    var key: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     value =  unboxer.unbox(key: "value")
     listValue =  unboxer.unbox(key: "listValue")
     key =  unboxer.unbox(key: "key")
  }
}
