// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Keyword :Unboxable {
    var type: String?
    var value: String?
  init(unboxer: Unboxer) throws { 
     type =  unboxer.unbox(key: "type")
     value =  unboxer.unbox(key: "value")
  }
}
