// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class List: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var key: String?
    var numitems: String?
    var list: [CmsItem?]?
    var blurb: String?
    var aliasList: [CmsItem?]?
}
