// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct List :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var key: String?
    var numitems: String?
    var list: [CmsItem?]?
    var blurb: String?
    var aliasList: [CmsItem?]?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     key =  unboxer.unbox(key: "key")
     numitems =  unboxer.unbox(key: "numitems")
     list =  unboxer.unbox(key: "list")
     blurb =  unboxer.unbox(key: "blurb")
     aliasList =  unboxer.unbox(key: "aliasList")
  }
}
