// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class MasterCut: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var aspectRatio: String?
    var height: Int?
    var width: Int?
    var x1: Int?
    var y1: Int?
}
