// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MasterCut :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var aspectRatio: String?
    var height: Int?
    var width: Int?
    var x1: Int?
    var y1: Int?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     aspectRatio =  unboxer.unbox(key: "aspectRatio")
     height =  unboxer.unbox(key: "height")
     width =  unboxer.unbox(key: "width")
     x1 =  unboxer.unbox(key: "x1")
     y1 =  unboxer.unbox(key: "y1")
  }
}
