// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

protocol Media {
    var contentId: String
    var displayRunTime: String?
    var genres: [String?]?
    var programId: String?
    var runTime: String?
    var type: String
}
