// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MediaAsset :CmsItem,PlayableMedia {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var mediaId: String?
    var milestones: [Milestone?]?
    var playbackUrls: [HypermediaLink?]?
    var audioType: String?
    var captions: String?
    var dubbedLanguages: String?
    var HDContent: Bool?
    var language: String?
    var mediaState: String?
    var secure: Bool?
    var subtitleLanguages: String?
    var mediaAssetType: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     mediaId =  unboxer.unbox(key: "mediaId")
     milestones =  unboxer.unbox(key: "milestones")
     playbackUrls =  unboxer.unbox(key: "playbackUrls")
     audioType =  unboxer.unbox(key: "audioType")
     captions =  unboxer.unbox(key: "captions")
     dubbedLanguages =  unboxer.unbox(key: "dubbedLanguages")
     HDContent =  unboxer.unbox(key: "HDContent")
     language =  unboxer.unbox(key: "language")
     mediaState =  unboxer.unbox(key: "mediaState")
     secure =  unboxer.unbox(key: "secure")
     subtitleLanguages =  unboxer.unbox(key: "subtitleLanguages")
     mediaAssetType =  unboxer.unbox(key: "mediaAssetType")
  }
}
