// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MediaUser :Unboxable {
    var userId: String?
    var lastWatched: Date?
    var percentCompleted: Float?
    var onWatchlist: Bool?
    var secondsWatched: Int?
  init(unboxer: Unboxer) throws { 
     userId =  unboxer.unbox(key: "userId")
     lastWatched =  unboxer.unbox(key: "lastWatched")
     percentCompleted =  unboxer.unbox(key: "percentCompleted")
     onWatchlist =  unboxer.unbox(key: "onWatchlist")
     secondsWatched =  unboxer.unbox(key: "secondsWatched")
  }
}
