// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

enum MediaRight: String {
    case GeoMediaRight = "GeoMediaRight"
    case EntitlementMediaRight = "EntitlementMediaRight"
    case BlackoutMediaRight = "BlackoutMediaRight"
}
