// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MediaList :Unboxable {
    var name: String?
    var videos: [Media?]?
  init(unboxer: Unboxer) throws { 
     name =  unboxer.unbox(key: "name")
     videos =  unboxer.unbox(key: "videos")
  }
}
