// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

enum MediaRight :String {
    case GeoMediaRight = "GeoMediaRight"
    case EntitlementMediaRight = "EntitlementMediaRight"
    case BlackoutMediaRight = "BlackoutMediaRight"
  init(unboxer: Unboxer) throws { 

  }
}
