// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class MediaAsset: CmsItem,PlayableMedia {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var mediaId: String?
    var milestones: [Milestone?]?
    var playbackUrls: [HypermediaLink?]?
    var audioType: String?
    var captions: String?
    var dubbedLanguages: String?
    var HDContent: Bool?
    var language: String?
    var mediaState: String?
    var secure: Bool?
    var subtitleLanguages: String?
    var mediaAssetType: String?
}
