// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MediaHit :Unboxable {
    var hit: Watchable?
    var user: MediaUser?
    var meta: SearchHitMeta?
  init(unboxer: Unboxer) throws { 
     hit =  unboxer.unbox(key: "hit")
     user =  unboxer.unbox(key: "user")
     meta =  unboxer.unbox(key: "meta")
  }
}
