// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MetaDeletion :Unboxable {
    var errorMessages: [String?]?
    var deletionsAttempted: Int?
    var deletionsSucceeded: Int?
  init(unboxer: Unboxer) throws { 
     errorMessages =  unboxer.unbox(key: "errorMessages")
     deletionsAttempted =  unboxer.unbox(key: "deletionsAttempted")
     deletionsSucceeded =  unboxer.unbox(key: "deletionsSucceeded")
  }
}
