// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MetaWatchlistAdd :Unboxable {
    var errorMessages: [String?]?
    var additionsAttempted: Int?
    var additionsSucceeded: Int?
  init(unboxer: Unboxer) throws { 
     errorMessages =  unboxer.unbox(key: "errorMessages")
     additionsAttempted =  unboxer.unbox(key: "additionsAttempted")
     additionsSucceeded =  unboxer.unbox(key: "additionsSucceeded")
  }
}
