// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct MilestoneTime :Unboxable {
    var type: String?
    var startDatetime: String?
    var start: Int?
  init(unboxer: Unboxer) throws { 
     type =  unboxer.unbox(key: "type")
     startDatetime =  unboxer.unbox(key: "startDatetime")
     start =  unboxer.unbox(key: "start")
  }
}
