// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Milestone :Unboxable {
    var photos: [PhotoAsset?]?
    var blurb: String?
    var id: String
    var keywords: [Keyword?]?
    var milestoneTime: [MilestoneTime?]?
    var milestoneType: String?
    var title: String?
  init(unboxer: Unboxer) throws { 
     photos =  unboxer.unbox(key: "photos")
     blurb =  unboxer.unbox(key: "blurb")
     id = try unboxer.unbox(key: "id")
     keywords =  unboxer.unbox(key: "keywords")
     milestoneTime =  unboxer.unbox(key: "milestoneTime")
     milestoneType =  unboxer.unbox(key: "milestoneType")
     title =  unboxer.unbox(key: "title")
  }
}
