// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Milestone {
    var photos: [PhotoAsset?]?
    var blurb: String?
    var id: String
    var keywords: [Keyword?]?
    var milestoneTime: [MilestoneTime?]?
    var milestoneType: String?
    var title: String?
}
