// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Page :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var body: String?
    var blurb: String?
    var noFollow: Bool?
    var seoKeywords: String?
    var seoBlurb: String?
    var seoTitle: String?
    var title: String?
    var key: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     body =  unboxer.unbox(key: "body")
     blurb =  unboxer.unbox(key: "blurb")
     noFollow =  unboxer.unbox(key: "noFollow")
     seoKeywords =  unboxer.unbox(key: "seoKeywords")
     seoBlurb =  unboxer.unbox(key: "seoBlurb")
     seoTitle =  unboxer.unbox(key: "seoTitle")
     title =  unboxer.unbox(key: "title")
     key =  unboxer.unbox(key: "key")
  }
}
