// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Page: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var body: String?
    var blurb: String?
    var noFollow: Bool?
    var seoKeywords: String?
    var seoBlurb: String?
    var seoTitle: String?
    var title: String?
    var key: String?
}
