// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Param :Unboxable {
    var name: String?
    var description: String?
  init(unboxer: Unboxer) throws { 
     name =  unboxer.unbox(key: "name")
     description =  unboxer.unbox(key: "description")
  }
}
