// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class PhotoAsset: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var altText: String?
    var caption: String?
    var credit: String?
    var headline: String?
    var rawImage: String?
    var width: Int?
    var height: Int?
    var inning: String?
    var purchaseUrl: String?
    var masterCuts: [MasterCut?]?
    var photos: [Photo?]?
    var timestamp: String?
    var title: String?
}
