// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class PhotoTemplate: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var templateKey: String?
    var aspectRatios: [TemplateAspectRatio?]?
}
