// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct PhotoAsset :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var altText: String?
    var caption: String?
    var credit: String?
    var headline: String?
    var rawImage: String?
    var width: Int?
    var height: Int?
    var inning: String?
    var purchaseUrl: String?
    var masterCuts: [MasterCut?]?
    var photos: [Photo?]?
    var timestamp: String?
    var title: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     altText =  unboxer.unbox(key: "altText")
     caption =  unboxer.unbox(key: "caption")
     credit =  unboxer.unbox(key: "credit")
     headline =  unboxer.unbox(key: "headline")
     rawImage =  unboxer.unbox(key: "rawImage")
     width =  unboxer.unbox(key: "width")
     height =  unboxer.unbox(key: "height")
     inning =  unboxer.unbox(key: "inning")
     purchaseUrl =  unboxer.unbox(key: "purchaseUrl")
     masterCuts =  unboxer.unbox(key: "masterCuts")
     photos =  unboxer.unbox(key: "photos")
     timestamp =  unboxer.unbox(key: "timestamp")
     title =  unboxer.unbox(key: "title")
  }
}
