// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

protocol PlayableMedia :Unboxable {
    var contentId: String
    var mediaId: String?
    var milestones: [Milestone?]?
    var playbackUrls: [HypermediaLink?]?
    var type: String
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     mediaId =  unboxer.unbox(key: "mediaId")
     milestones =  unboxer.unbox(key: "milestones")
     playbackUrls =  unboxer.unbox(key: "playbackUrls")
     type = try unboxer.unbox(key: "type")
  }
}
