// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

protocol PlayableMedia {
    var contentId: String
    var mediaId: String?
    var milestones: [Milestone?]?
    var playbackUrls: [HypermediaLink?]?
    var type: String
}
