// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct PostPlayResponse :Unboxable {
    var meta: Meta?
    var content: VideoAiring?
  init(unboxer: Unboxer) throws { 
     meta =  unboxer.unbox(key: "meta")
     content =  unboxer.unbox(key: "content")
  }
}
