// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct QueryResponse :SearchResponse {
    var meta: SearchResponseMeta?
    var query: SearchIndexQuery?
    var entities: RecognizedEntities?
    var facets: [SearchResponseFacet?]?
    var hits: [SearchHit?]?
    var user: User?
  init(unboxer: Unboxer) throws { 
     meta =  unboxer.unbox(key: "meta")
     query =  unboxer.unbox(key: "query")
     entities =  unboxer.unbox(key: "entities")
     facets =  unboxer.unbox(key: "facets")
     hits =  unboxer.unbox(key: "hits")
     user =  unboxer.unbox(key: "user")
  }
}
