// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class SearchResponseMeta {
    var hits: Int?
    var time: Int?
    var page_size: Int?
    var offset: Int?
    var errors: [String?]?
}
