// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct SearchResponseFacetValue :Unboxable {
    var count: Int?
    var value: OmniScalar?
  init(unboxer: Unboxer) throws { 
     count =  unboxer.unbox(key: "count")
     value =  unboxer.unbox(key: "value")
  }
}
