// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class SearchMutation {
    var deleteBookmarks: DeleteBookmarks?
    var deleteAllBookmarks: DeleteAllBookmarks?
    var addToWatchlist: AddToWatchlist?
    var deleteFromWatchlist: DeleteFromWatchlist?
    var clearWatchlist: ClearWatchlist?
}
