// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct SearchQuery :Unboxable {
    var query: QueryResponse?
    var prefix: PrefixResponse?
    var sitesearch: SitesearchResponse?
    var bucket: TopFoundHitsResponse?
    var bookmarks: MediaResponse?
    var watchlist: MediaResponse?
    var Airings: [Airing?]?
    var CategoryAll: [Category?]?
    var CategoryByContentId: Category?
    var CategoryBySport: [Category?]?
    var ChannelAll: [Channel?]?
    var ChannelByContentId: Channel?
    var CollectionAll: [Collection?]?
    var CollectionByContentId: Collection?
    var ConfigurationJsonByContentId: ConfigurationJson?
    var ConfigurationJsonByResourceKey: ConfigurationJson?
    var ConfigurationStructuredByContentId: ConfigurationStructured?
    var DimensionByContentId: Dimension?
    var EventPageAll: [EventPage?]?
    var EventPageByContentId: EventPage?
    var EventPageByLanguage: [EventPage?]?
    var FieldOptionByContentId: FieldOption?
    var KeyValueByContentId: KeyValue?
    var ListByContentId: List?
    var ListByTitle: List?
    var MasterCutByContentId: MasterCut?
    var Media: [MediaList?]?
    var MediaAssetByContentId: MediaAsset?
    var PageByContentId: Page?
    var PageByResourceKey: Page?
    var PhotoAssetByContentId: PhotoAsset?
    var PhotoByContentId: Photo?
    var PhotoTemplateByContentId: PhotoTemplate?
    var postplay: PostPlayResponse?
    var Schedule: [ChannelSchedule?]?
    var SeasonAll: [Season?]?
    var SeasonByContentId: Season?
    var SeasonBySeasonId: [Season?]?
    var SeasonBySeasonIdAndLanguage: Season?
    var SeasonBySeriesSlug: [Season?]?
    var SeasonContainerByContentId: SeasonContainer?
    var SectionByContentId: Section?
    var SeriesAll: [Series?]?
    var SeriesByCategory: [Series?]?
    var SeriesByContentId: Series?
    var SeriesByGenre: [Series?]?
    var SeriesBySeriesId: [Series?]?
    var SeriesBySeriesIdAndLanguage: Series?
    var SeriesBySeriesSlug: [Series?]?
    var SeriesContainerByContentId: SeriesContainer?
    var ShortContentByContentId: ShortContent?
    var TemplateAspectRatioByContentId: TemplateAspectRatio?
    var TitleAssetByContentId: TitleAsset?
    var VideoAll: [Video?]?
    var VideoByCategory: [Video?]?
    var VideoByContentId: Video?
    var VideoByEpgPartnerProgramId: [Video?]?
    var VideoByGenre: [Video?]?
    var VideoByGroupingId: [Video?]?
    var VideoByPartnerProgramId: [Video?]?
    var VideoBySeasonId: [Video?]?
    var VideoBySeriesId: [Video?]?
    var VideoBySeriesSlug: [Video?]?
    var videodetails: [VideoDetail?]?
  init(unboxer: Unboxer) throws { 
     query =  unboxer.unbox(key: "query")
     prefix =  unboxer.unbox(key: "prefix")
     sitesearch =  unboxer.unbox(key: "sitesearch")
     bucket =  unboxer.unbox(key: "bucket")
     bookmarks =  unboxer.unbox(key: "bookmarks")
     watchlist =  unboxer.unbox(key: "watchlist")
     Airings =  unboxer.unbox(key: "Airings")
     CategoryAll =  unboxer.unbox(key: "CategoryAll")
     CategoryByContentId =  unboxer.unbox(key: "CategoryByContentId")
     CategoryBySport =  unboxer.unbox(key: "CategoryBySport")
     ChannelAll =  unboxer.unbox(key: "ChannelAll")
     ChannelByContentId =  unboxer.unbox(key: "ChannelByContentId")
     CollectionAll =  unboxer.unbox(key: "CollectionAll")
     CollectionByContentId =  unboxer.unbox(key: "CollectionByContentId")
     ConfigurationJsonByContentId =  unboxer.unbox(key: "ConfigurationJsonByContentId")
     ConfigurationJsonByResourceKey =  unboxer.unbox(key: "ConfigurationJsonByResourceKey")
     ConfigurationStructuredByContentId =  unboxer.unbox(key: "ConfigurationStructuredByContentId")
     DimensionByContentId =  unboxer.unbox(key: "DimensionByContentId")
     EventPageAll =  unboxer.unbox(key: "EventPageAll")
     EventPageByContentId =  unboxer.unbox(key: "EventPageByContentId")
     EventPageByLanguage =  unboxer.unbox(key: "EventPageByLanguage")
     FieldOptionByContentId =  unboxer.unbox(key: "FieldOptionByContentId")
     KeyValueByContentId =  unboxer.unbox(key: "KeyValueByContentId")
     ListByContentId =  unboxer.unbox(key: "ListByContentId")
     ListByTitle =  unboxer.unbox(key: "ListByTitle")
     MasterCutByContentId =  unboxer.unbox(key: "MasterCutByContentId")
     Media =  unboxer.unbox(key: "Media")
     MediaAssetByContentId =  unboxer.unbox(key: "MediaAssetByContentId")
     PageByContentId =  unboxer.unbox(key: "PageByContentId")
     PageByResourceKey =  unboxer.unbox(key: "PageByResourceKey")
     PhotoAssetByContentId =  unboxer.unbox(key: "PhotoAssetByContentId")
     PhotoByContentId =  unboxer.unbox(key: "PhotoByContentId")
     PhotoTemplateByContentId =  unboxer.unbox(key: "PhotoTemplateByContentId")
     postplay =  unboxer.unbox(key: "postplay")
     Schedule =  unboxer.unbox(key: "Schedule")
     SeasonAll =  unboxer.unbox(key: "SeasonAll")
     SeasonByContentId =  unboxer.unbox(key: "SeasonByContentId")
     SeasonBySeasonId =  unboxer.unbox(key: "SeasonBySeasonId")
     SeasonBySeasonIdAndLanguage =  unboxer.unbox(key: "SeasonBySeasonIdAndLanguage")
     SeasonBySeriesSlug =  unboxer.unbox(key: "SeasonBySeriesSlug")
     SeasonContainerByContentId =  unboxer.unbox(key: "SeasonContainerByContentId")
     SectionByContentId =  unboxer.unbox(key: "SectionByContentId")
     SeriesAll =  unboxer.unbox(key: "SeriesAll")
     SeriesByCategory =  unboxer.unbox(key: "SeriesByCategory")
     SeriesByContentId =  unboxer.unbox(key: "SeriesByContentId")
     SeriesByGenre =  unboxer.unbox(key: "SeriesByGenre")
     SeriesBySeriesId =  unboxer.unbox(key: "SeriesBySeriesId")
     SeriesBySeriesIdAndLanguage =  unboxer.unbox(key: "SeriesBySeriesIdAndLanguage")
     SeriesBySeriesSlug =  unboxer.unbox(key: "SeriesBySeriesSlug")
     SeriesContainerByContentId =  unboxer.unbox(key: "SeriesContainerByContentId")
     ShortContentByContentId =  unboxer.unbox(key: "ShortContentByContentId")
     TemplateAspectRatioByContentId =  unboxer.unbox(key: "TemplateAspectRatioByContentId")
     TitleAssetByContentId =  unboxer.unbox(key: "TitleAssetByContentId")
     VideoAll =  unboxer.unbox(key: "VideoAll")
     VideoByCategory =  unboxer.unbox(key: "VideoByCategory")
     VideoByContentId =  unboxer.unbox(key: "VideoByContentId")
     VideoByEpgPartnerProgramId =  unboxer.unbox(key: "VideoByEpgPartnerProgramId")
     VideoByGenre =  unboxer.unbox(key: "VideoByGenre")
     VideoByGroupingId =  unboxer.unbox(key: "VideoByGroupingId")
     VideoByPartnerProgramId =  unboxer.unbox(key: "VideoByPartnerProgramId")
     VideoBySeasonId =  unboxer.unbox(key: "VideoBySeasonId")
     VideoBySeriesId =  unboxer.unbox(key: "VideoBySeriesId")
     VideoBySeriesSlug =  unboxer.unbox(key: "VideoBySeriesSlug")
     videodetails =  unboxer.unbox(key: "videodetails")
  }
}
