// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class SearchHitMeta {
    var id: String?
    var type: String?
    var url: String?
    var title: String?
    var snippet: String?
    var language: String?
    var publish_timestamp: Date?
    var display_timestamp: Date?
    var update_timestamp: Date?
    var sort_timestamp: Date?
    var score: Float?
    var tags: [SearchHitMetaTag?]?
    var image: [ImageCut?]?
}
