// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct SearchHit :Unboxable {
    var user: MetaUser?
    var meta: SearchHitMeta?
    var hit: SearchResultDoc?
  init(unboxer: Unboxer) throws { 
     user =  unboxer.unbox(key: "user")
     meta =  unboxer.unbox(key: "meta")
     hit =  unboxer.unbox(key: "hit")
  }
}
