// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct SearchHitMeta :Unboxable {
    var id: String?
    var type: String?
    var url: String?
    var title: String?
    var snippet: String?
    var language: String?
    var publish_timestamp: Date?
    var display_timestamp: Date?
    var update_timestamp: Date?
    var sort_timestamp: Date?
    var score: Float?
    var tags: [SearchHitMetaTag?]?
    var image: [ImageCut?]?
  init(unboxer: Unboxer) throws { 
     id =  unboxer.unbox(key: "id")
     type =  unboxer.unbox(key: "type")
     url =  unboxer.unbox(key: "url")
     title =  unboxer.unbox(key: "title")
     snippet =  unboxer.unbox(key: "snippet")
     language =  unboxer.unbox(key: "language")
     publish_timestamp =  unboxer.unbox(key: "publish_timestamp")
     display_timestamp =  unboxer.unbox(key: "display_timestamp")
     update_timestamp =  unboxer.unbox(key: "update_timestamp")
     sort_timestamp =  unboxer.unbox(key: "sort_timestamp")
     score =  unboxer.unbox(key: "score")
     tags =  unboxer.unbox(key: "tags")
     image =  unboxer.unbox(key: "image")
  }
}
