// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct SearchResponseFacet :Unboxable {
    var field: String?
    var values: [SearchResponseFacetValue?]?
  init(unboxer: Unboxer) throws { 
     field =  unboxer.unbox(key: "field")
     values =  unboxer.unbox(key: "values")
  }
}
