// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct SearchMutation :Unboxable {
    var deleteBookmarks: DeleteBookmarks?
    var deleteAllBookmarks: DeleteAllBookmarks?
    var addToWatchlist: AddToWatchlist?
    var deleteFromWatchlist: DeleteFromWatchlist?
    var clearWatchlist: ClearWatchlist?
  init(unboxer: Unboxer) throws { 
     deleteBookmarks =  unboxer.unbox(key: "deleteBookmarks")
     deleteAllBookmarks =  unboxer.unbox(key: "deleteAllBookmarks")
     addToWatchlist =  unboxer.unbox(key: "addToWatchlist")
     deleteFromWatchlist =  unboxer.unbox(key: "deleteFromWatchlist")
     clearWatchlist =  unboxer.unbox(key: "clearWatchlist")
  }
}
