// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Season: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var photos: [PhotoAsset?]?
    var seasonTitle: String?
    var seasonBrief: String?
    var seasonSortName: String?
    var summaryShort: String?
    var summaryLong: String?
    var language: String?
    var seriesId: String?
    var seasonId: String?
    var seasonSequenceNumber: Int?
    var slug: String?
}
