// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Season :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var photos: [PhotoAsset?]?
    var seasonTitle: String?
    var seasonBrief: String?
    var seasonSortName: String?
    var summaryShort: String?
    var summaryLong: String?
    var language: String?
    var seriesId: String?
    var seasonId: String?
    var seasonSequenceNumber: Int?
    var slug: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     photos =  unboxer.unbox(key: "photos")
     seasonTitle =  unboxer.unbox(key: "seasonTitle")
     seasonBrief =  unboxer.unbox(key: "seasonBrief")
     seasonSortName =  unboxer.unbox(key: "seasonSortName")
     summaryShort =  unboxer.unbox(key: "summaryShort")
     summaryLong =  unboxer.unbox(key: "summaryLong")
     language =  unboxer.unbox(key: "language")
     seriesId =  unboxer.unbox(key: "seriesId")
     seasonId =  unboxer.unbox(key: "seasonId")
     seasonSequenceNumber =  unboxer.unbox(key: "seasonSequenceNumber")
     slug =  unboxer.unbox(key: "slug")
  }
}
