// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Section: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var photos: [PhotoAsset?]?
    var url: String?
    var title: String?
    var key: String?
    var list: [CmsItem?]?
}
