// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Section :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var photos: [PhotoAsset?]?
    var url: String?
    var title: String?
    var key: String?
    var list: [CmsItem?]?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     photos =  unboxer.unbox(key: "photos")
     url =  unboxer.unbox(key: "url")
     title =  unboxer.unbox(key: "title")
     key =  unboxer.unbox(key: "key")
     list =  unboxer.unbox(key: "list")
  }
}
