// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class Series: CmsItem,WatchlistPersonalizedHit {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var user: WatchlistUser?
    var photos: [PhotoAsset?]?
    var seriesTitle: String?
    var seriesBrief: String?
    var seriesSortName: String?
    var summaryShort: String?
    var summaryLong: String?
    var language: String?
    var seriesId: String?
    var seriesSequenceNumber: Int?
    var genre: String?
    var genres: [String?]?
    var category: String?
    var slug: String?
    var seriesSlug: String?
}
