// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Series :CmsItem,WatchlistPersonalizedHit {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var user: WatchlistUser?
    var photos: [PhotoAsset?]?
    var seriesTitle: String?
    var seriesBrief: String?
    var seriesSortName: String?
    var summaryShort: String?
    var summaryLong: String?
    var language: String?
    var seriesId: String?
    var seriesSequenceNumber: Int?
    var genre: String?
    var genres: [String?]?
    var category: String?
    var slug: String?
    var seriesSlug: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     user =  unboxer.unbox(key: "user")
     photos =  unboxer.unbox(key: "photos")
     seriesTitle =  unboxer.unbox(key: "seriesTitle")
     seriesBrief =  unboxer.unbox(key: "seriesBrief")
     seriesSortName =  unboxer.unbox(key: "seriesSortName")
     summaryShort =  unboxer.unbox(key: "summaryShort")
     summaryLong =  unboxer.unbox(key: "summaryLong")
     language =  unboxer.unbox(key: "language")
     seriesId =  unboxer.unbox(key: "seriesId")
     seriesSequenceNumber =  unboxer.unbox(key: "seriesSequenceNumber")
     genre =  unboxer.unbox(key: "genre")
     genres =  unboxer.unbox(key: "genres")
     category =  unboxer.unbox(key: "category")
     slug =  unboxer.unbox(key: "slug")
     seriesSlug =  unboxer.unbox(key: "seriesSlug")
  }
}
