// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class ShortContent: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var photos: [PhotoAsset?]?
    var list: [CmsItem?]?
    var blurb: String?
    var headline: String?
    var assets: [CmsItem?]?
}
