// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct ShortContent :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var photos: [PhotoAsset?]?
    var list: [CmsItem?]?
    var blurb: String?
    var headline: String?
    var assets: [CmsItem?]?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     photos =  unboxer.unbox(key: "photos")
     list =  unboxer.unbox(key: "list")
     blurb =  unboxer.unbox(key: "blurb")
     headline =  unboxer.unbox(key: "headline")
     assets =  unboxer.unbox(key: "assets")
  }
}
