// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class SitesearchResponse: SearchResponse {
    var meta: SearchResponseMeta?
    var query: SearchIndexQuery?
    var entities: RecognizedEntities?
    var facets: [SearchResponseFacet?]?
    var hits: [SearchHit?]?
    var user: User?
}
