// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

enum SortDirection :String {
    case Ascending = "Ascending"
    case Descending = "Descending"
  init(unboxer: Unboxer) throws { 

  }
}
