// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class TitleAsset: CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var episodeName: String?
    var summaryLong: String?
    var summaryShort: String?
    var title: String?
    var titleBrief: String?
    var titleSortName: String?
    var language: String?
    var slug: String?
    var titleSlug: String?
}
