// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct TitleAsset :CmsItem {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var episodeName: String?
    var summaryLong: String?
    var summaryShort: String?
    var title: String?
    var titleBrief: String?
    var titleSortName: String?
    var language: String?
    var slug: String?
    var titleSlug: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     episodeName =  unboxer.unbox(key: "episodeName")
     summaryLong =  unboxer.unbox(key: "summaryLong")
     summaryShort =  unboxer.unbox(key: "summaryShort")
     title =  unboxer.unbox(key: "title")
     titleBrief =  unboxer.unbox(key: "titleBrief")
     titleSortName =  unboxer.unbox(key: "titleSortName")
     language =  unboxer.unbox(key: "language")
     slug =  unboxer.unbox(key: "slug")
     titleSlug =  unboxer.unbox(key: "titleSlug")
  }
}
