// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class TopFoundHitsResponse {
    var meta: SearchResponseMeta?
    var query: SearchIndexQuery?
    var aggs: [TopFoundHitsAgg?]?
    var entities: RecognizedEntities?
}
