// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct TopFoundHitsResponse :Unboxable {
    var meta: SearchResponseMeta?
    var query: SearchIndexQuery?
    var aggs: [TopFoundHitsAgg?]?
    var entities: RecognizedEntities?
  init(unboxer: Unboxer) throws { 
     meta =  unboxer.unbox(key: "meta")
     query =  unboxer.unbox(key: "query")
     aggs =  unboxer.unbox(key: "aggs")
     entities =  unboxer.unbox(key: "entities")
  }
}
