// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct TopFoundHitsBucket :Unboxable {
    var value: String?
    var count: Int?
    var hits: [SearchHit?]?
  init(unboxer: Unboxer) throws { 
     value =  unboxer.unbox(key: "value")
     count =  unboxer.unbox(key: "count")
     hits =  unboxer.unbox(key: "hits")
  }
}
