// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Url :Unboxable {
    var rel: String?
    var href: String?
  init(unboxer: Unboxer) throws { 
     rel =  unboxer.unbox(key: "rel")
     href =  unboxer.unbox(key: "href")
  }
}
