// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct User :Unboxable {
    var userId: String?
  init(unboxer: Unboxer) throws { 
     userId =  unboxer.unbox(key: "userId")
  }
}
