// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct VideoAiringPairing :Unboxable {
    var video: Video?
    var airing: Airing?
  init(unboxer: Unboxer) throws { 
     video =  unboxer.unbox(key: "video")
     airing =  unboxer.unbox(key: "airing")
  }
}
