// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct Video :CmsItem,Media,WatchlistBookmarksPersonalizedHit {
    var contentId: String
    var type: String
    var tags: [Tag]?
    var displayRunTime: String?
    var genres: [String?]?
    var programId: String?
    var runTime: String?
    var user: WatchlistBookmarksUser?
    var photos: [PhotoAsset?]?
    var actorsDisplay: String?
    var appears: String?
    var assetName: String?
    var billingID: String?
    var calendarEventId: String?
    var closedCaptioning: Bool?
    var creationDate: String?
    var description: String?
    var displayAsLastChance: Bool?
    var displayAsNew: Bool?
    var epgPartnerProgramId: String?
    var partnerProgramId: String?
    var episodeId: String?
    var episodeName: String?
    var episodeSequenceNumber: Int?
    var expires: String?
    var keywords: [String?]?
    var keywordsMediaRights: String?
    var language: String?
    var media: [MediaAsset?]?
    var milestoneStart: MilestoneMarker?
    var milestoneEnd: MilestoneMarker?
    var product: String?
    var provider: String?
    var providerID: String?
    var providerQAContact: String?
    var ratings: [Rating?]?
    var releaseDate: String?
    var seasonFinale: Bool?
    var seasonId: String?
    var seriesId: String?
    var seasonPremiere: Bool?
    var slates: [Slate?]?
    var studio: String?
    var studioCode: String?
    var studioName: String?
    var titles: [TitleAsset?]?
    var writerDisplay: String?
    var series_slug: String?
    var season_slug: String?
    var seriesSlug: String?
    var seasonSlug: String?
  init(unboxer: Unboxer) throws { 
     contentId = try unboxer.unbox(key: "contentId")
     type = try unboxer.unbox(key: "type")
     tags =  unboxer.unbox(key: "tags")
     displayRunTime =  unboxer.unbox(key: "displayRunTime")
     genres =  unboxer.unbox(key: "genres")
     programId =  unboxer.unbox(key: "programId")
     runTime =  unboxer.unbox(key: "runTime")
     user =  unboxer.unbox(key: "user")
     photos =  unboxer.unbox(key: "photos")
     actorsDisplay =  unboxer.unbox(key: "actorsDisplay")
     appears =  unboxer.unbox(key: "appears")
     assetName =  unboxer.unbox(key: "assetName")
     billingID =  unboxer.unbox(key: "billingID")
     calendarEventId =  unboxer.unbox(key: "calendarEventId")
     closedCaptioning =  unboxer.unbox(key: "closedCaptioning")
     creationDate =  unboxer.unbox(key: "creationDate")
     description =  unboxer.unbox(key: "description")
     displayAsLastChance =  unboxer.unbox(key: "displayAsLastChance")
     displayAsNew =  unboxer.unbox(key: "displayAsNew")
     epgPartnerProgramId =  unboxer.unbox(key: "epgPartnerProgramId")
     partnerProgramId =  unboxer.unbox(key: "partnerProgramId")
     episodeId =  unboxer.unbox(key: "episodeId")
     episodeName =  unboxer.unbox(key: "episodeName")
     episodeSequenceNumber =  unboxer.unbox(key: "episodeSequenceNumber")
     expires =  unboxer.unbox(key: "expires")
     keywords =  unboxer.unbox(key: "keywords")
     keywordsMediaRights =  unboxer.unbox(key: "keywordsMediaRights")
     language =  unboxer.unbox(key: "language")
     media =  unboxer.unbox(key: "media")
     milestoneStart =  unboxer.unbox(key: "milestoneStart")
     milestoneEnd =  unboxer.unbox(key: "milestoneEnd")
     product =  unboxer.unbox(key: "product")
     provider =  unboxer.unbox(key: "provider")
     providerID =  unboxer.unbox(key: "providerID")
     providerQAContact =  unboxer.unbox(key: "providerQAContact")
     ratings =  unboxer.unbox(key: "ratings")
     releaseDate =  unboxer.unbox(key: "releaseDate")
     seasonFinale =  unboxer.unbox(key: "seasonFinale")
     seasonId =  unboxer.unbox(key: "seasonId")
     seriesId =  unboxer.unbox(key: "seriesId")
     seasonPremiere =  unboxer.unbox(key: "seasonPremiere")
     slates =  unboxer.unbox(key: "slates")
     studio =  unboxer.unbox(key: "studio")
     studioCode =  unboxer.unbox(key: "studioCode")
     studioName =  unboxer.unbox(key: "studioName")
     titles =  unboxer.unbox(key: "titles")
     writerDisplay =  unboxer.unbox(key: "writerDisplay")
     series_slug =  unboxer.unbox(key: "series_slug")
     season_slug =  unboxer.unbox(key: "season_slug")
     seriesSlug =  unboxer.unbox(key: "seriesSlug")
     seasonSlug =  unboxer.unbox(key: "seasonSlug")
  }
}
