// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

protocol WatchlistBookmarksPersonalizedHit :Unboxable {
    var user: WatchlistBookmarksUser?
  init(unboxer: Unboxer) throws { 
     user =  unboxer.unbox(key: "user")
  }
}
