// generated by graphql-swift-codegen at 2017-09-29 13:44:23 +0000

class WatchlistBookmarksUser: WatchlistMethods {
    var onWatchlist: Bool?
    var lastWatched: Date?
    var percentCompleted: Float?
    var secondsWatched: Int?
}
