// generated by graphql-swift-codegen at 2017-09-29 21:10:15 +0000


import Unbox

struct WatchlistUser :WatchlistMethods {
    var onWatchlist: Bool?
  init(unboxer: Unboxer) throws { 
     onWatchlist =  unboxer.unbox(key: "onWatchlist")
  }
}
